use chrono::{DateTime, Utc};
use hmacs_core::{AlertId, AssetSymbol, ParticipantId, TransactionId};
use rust_decimal::Decimal;
use rust_decimal_macros::dec;
use serde::{Deserialize, Serialize};

use crate::jurisdiction::Jurisdiction;

/// Types of suspicious activity patterns.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AlertType {
    /// Transaction exceeds large-transaction reporting threshold
    LargeTransaction,
    /// Multiple transactions just below reporting threshold (structuring)
    Structuring,
    /// Unusually rapid succession of transactions
    RapidTransactions,
    /// Transaction with sanctioned/high-risk jurisdiction
    HighRiskJurisdiction,
    /// Unusual pattern for the participant's profile
    UnusualPattern,
    /// First-time large transaction for a new account
    NewAccountLargeTx,
    /// Round-trip transaction (funds sent and returned quickly)
    RoundTrip,
    /// Dormant account suddenly active
    DormantReactivation,
    /// Aggregate daily volume exceeds threshold
    DailyVolumeExceeded,
    /// KYC information mismatch or inconsistency
    KycInconsistency,
}

impl std::fmt::Display for AlertType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            Self::LargeTransaction => "large_transaction",
            Self::Structuring => "structuring",
            Self::RapidTransactions => "rapid_transactions",
            Self::HighRiskJurisdiction => "high_risk_jurisdiction",
            Self::UnusualPattern => "unusual_pattern",
            Self::NewAccountLargeTx => "new_account_large_tx",
            Self::RoundTrip => "round_trip",
            Self::DormantReactivation => "dormant_reactivation",
            Self::DailyVolumeExceeded => "daily_volume_exceeded",
            Self::KycInconsistency => "kyc_inconsistency",
        };
        write!(f, "{}", s)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AlertSeverity {
    Low,
    Medium,
    High,
    Critical,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AlertStatus {
    Open,
    UnderReview,
    Escalated,
    /// Requires SAR/STR filing
    SarRequired,
    SarFiled,
    Dismissed,
    Resolved,
}

/// A compliance alert generated by the monitoring system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComplianceAlert {
    pub id: AlertId,
    pub participant_id: ParticipantId,
    pub alert_type: AlertType,
    pub severity: AlertSeverity,
    pub status: AlertStatus,
    pub jurisdiction: Jurisdiction,
    pub transaction_id: Option<TransactionId>,
    pub amount: Option<Decimal>,
    pub asset: Option<AssetSymbol>,
    pub description: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub reviewed_by: Option<String>,
    pub resolution_notes: Option<String>,
}

/// Transaction data fed into the monitoring engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MonitoredTransaction {
    pub transaction_id: TransactionId,
    pub participant_id: ParticipantId,
    pub counterparty_id: Option<ParticipantId>,
    pub direction: TransactionDirection,
    pub amount: Decimal,
    pub asset: AssetSymbol,
    pub jurisdiction: Jurisdiction,
    pub timestamp: DateTime<Utc>,
    pub wallet_address: Option<String>,
    pub counterparty_address: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TransactionDirection {
    Inbound,
    Outbound,
    Internal,
}

/// Configurable monitoring thresholds.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MonitoringConfig {
    /// Number of transactions within the window that triggers rapid-tx alert
    pub rapid_tx_count: u32,
    /// Window in seconds for rapid transaction detection
    pub rapid_tx_window_secs: u64,
    /// Percentage below threshold that triggers structuring suspicion
    pub structuring_margin_pct: Decimal,
    /// Daily aggregate volume ceiling (USDC equivalent)
    pub daily_volume_ceiling: Decimal,
    /// Account age in days below which large-tx triggers new-account alert
    pub new_account_threshold_days: u32,
    /// Days of inactivity before reactivation triggers alert
    pub dormant_threshold_days: u32,
}

impl Default for MonitoringConfig {
    fn default() -> Self {
        Self {
            rapid_tx_count: 10,
            rapid_tx_window_secs: 3600,
            structuring_margin_pct: dec!(0.10),
            daily_volume_ceiling: dec!(50000),
            new_account_threshold_days: 30,
            dormant_threshold_days: 90,
        }
    }
}

/// Evaluate a single transaction against monitoring rules.
/// Returns a list of alerts (may be empty if no rules triggered).
pub fn evaluate_transaction(
    tx: &MonitoredTransaction,
    jurisdiction_rules: &crate::jurisdiction::JurisdictionRules,
    _config: &MonitoringConfig,
    _recent_tx_count_in_window: u32,
    _daily_volume: Decimal,
    _account_age_days: u32,
) -> Vec<ComplianceAlert> {
    let mut alerts = Vec::new();

    // Rule 1: Large transaction reporting
    if jurisdiction_rules.requires_large_tx_report(tx.amount) {
        alerts.push(ComplianceAlert {
            id: AlertId::new(),
            participant_id: tx.participant_id,
            alert_type: AlertType::LargeTransaction,
            severity: AlertSeverity::High,
            status: AlertStatus::Open,
            jurisdiction: tx.jurisdiction,
            transaction_id: Some(tx.transaction_id),
            amount: Some(tx.amount),
            asset: Some(tx.asset),
            description: format!(
                "Transaction of {} {} exceeds {} reporting threshold of {} USDC",
                tx.amount, tx.asset, tx.jurisdiction, jurisdiction_rules.large_tx_report_threshold
            ),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            reviewed_by: None,
            resolution_notes: None,
        });
    }

    // Rule 2: Structuring detection — amount within margin below threshold
    let threshold = jurisdiction_rules.large_tx_report_threshold;
    let margin = threshold * _config.structuring_margin_pct;
    if tx.amount < threshold && tx.amount >= (threshold - margin) {
        alerts.push(ComplianceAlert {
            id: AlertId::new(),
            participant_id: tx.participant_id,
            alert_type: AlertType::Structuring,
            severity: AlertSeverity::Medium,
            status: AlertStatus::Open,
            jurisdiction: tx.jurisdiction,
            transaction_id: Some(tx.transaction_id),
            amount: Some(tx.amount),
            asset: Some(tx.asset),
            description: format!(
                "Transaction of {} {} is suspiciously close to the {} reporting threshold ({})",
                tx.amount, tx.asset, tx.jurisdiction, threshold
            ),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            reviewed_by: None,
            resolution_notes: None,
        });
    }

    // Rule 3: Rapid transactions
    if _recent_tx_count_in_window >= _config.rapid_tx_count {
        alerts.push(ComplianceAlert {
            id: AlertId::new(),
            participant_id: tx.participant_id,
            alert_type: AlertType::RapidTransactions,
            severity: AlertSeverity::Medium,
            status: AlertStatus::Open,
            jurisdiction: tx.jurisdiction,
            transaction_id: Some(tx.transaction_id),
            amount: Some(tx.amount),
            asset: Some(tx.asset),
            description: format!(
                "{} transactions within {} seconds window",
                _recent_tx_count_in_window, _config.rapid_tx_window_secs
            ),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            reviewed_by: None,
            resolution_notes: None,
        });
    }

    // Rule 4: Daily volume exceeded
    if _daily_volume + tx.amount > _config.daily_volume_ceiling {
        alerts.push(ComplianceAlert {
            id: AlertId::new(),
            participant_id: tx.participant_id,
            alert_type: AlertType::DailyVolumeExceeded,
            severity: AlertSeverity::High,
            status: AlertStatus::Open,
            jurisdiction: tx.jurisdiction,
            transaction_id: Some(tx.transaction_id),
            amount: Some(tx.amount),
            asset: Some(tx.asset),
            description: format!(
                "Daily volume {} + {} {} exceeds ceiling of {} USDC",
                _daily_volume, tx.amount, tx.asset, _config.daily_volume_ceiling
            ),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            reviewed_by: None,
            resolution_notes: None,
        });
    }

    // Rule 5: New account large transaction
    if _account_age_days < _config.new_account_threshold_days
        && tx.amount >= jurisdiction_rules.elevated_kyc_threshold
    {
        alerts.push(ComplianceAlert {
            id: AlertId::new(),
            participant_id: tx.participant_id,
            alert_type: AlertType::NewAccountLargeTx,
            severity: AlertSeverity::High,
            status: AlertStatus::Open,
            jurisdiction: tx.jurisdiction,
            transaction_id: Some(tx.transaction_id),
            amount: Some(tx.amount),
            asset: Some(tx.asset),
            description: format!(
                "Account is {} days old with a large transaction of {} {}",
                _account_age_days, tx.amount, tx.asset
            ),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            reviewed_by: None,
            resolution_notes: None,
        });
    }

    alerts
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::jurisdiction::JurisdictionRules;

    fn make_tx(amount: Decimal, jurisdiction: Jurisdiction) -> MonitoredTransaction {
        MonitoredTransaction {
            transaction_id: TransactionId::new(),
            participant_id: ParticipantId::new(),
            counterparty_id: None,
            direction: TransactionDirection::Outbound,
            amount,
            asset: AssetSymbol::Usdc,
            jurisdiction,
            timestamp: Utc::now(),
            wallet_address: None,
            counterparty_address: None,
        }
    }

    #[test]
    fn test_large_tx_alert_us() {
        let tx = make_tx(dec!(15000), Jurisdiction::Us);
        let rules = JurisdictionRules::us();
        let config = MonitoringConfig::default();
        let alerts = evaluate_transaction(&tx, &rules, &config, 0, dec!(0), 365);
        assert!(alerts.iter().any(|a| a.alert_type == AlertType::LargeTransaction));
    }

    #[test]
    fn test_no_alert_below_threshold() {
        let tx = make_tx(dec!(500), Jurisdiction::Us);
        let rules = JurisdictionRules::us();
        let config = MonitoringConfig::default();
        let alerts = evaluate_transaction(&tx, &rules, &config, 0, dec!(0), 365);
        assert!(alerts.is_empty());
    }

    #[test]
    fn test_structuring_detection() {
        let tx = make_tx(dec!(9500), Jurisdiction::Us);
        let rules = JurisdictionRules::us();
        let config = MonitoringConfig::default();
        let alerts = evaluate_transaction(&tx, &rules, &config, 0, dec!(0), 365);
        assert!(alerts.iter().any(|a| a.alert_type == AlertType::Structuring));
    }

    #[test]
    fn test_rapid_transactions() {
        let tx = make_tx(dec!(100), Jurisdiction::Eu);
        let rules = JurisdictionRules::eu();
        let config = MonitoringConfig::default();
        let alerts = evaluate_transaction(&tx, &rules, &config, 15, dec!(0), 365);
        assert!(alerts.iter().any(|a| a.alert_type == AlertType::RapidTransactions));
    }

    #[test]
    fn test_new_account_large_tx() {
        let tx = make_tx(dec!(12000), Jurisdiction::Sg);
        let rules = JurisdictionRules::sg();
        let config = MonitoringConfig::default();
        let alerts = evaluate_transaction(&tx, &rules, &config, 0, dec!(0), 5);
        assert!(alerts.is_empty()); // 12000 < 15000 (elevated_kyc_threshold)

        let tx_big = make_tx(dec!(20000), Jurisdiction::Sg);
        let alerts = evaluate_transaction(&tx_big, &rules, &config, 0, dec!(0), 5);
        assert!(alerts.iter().any(|a| a.alert_type == AlertType::NewAccountLargeTx));
    }
}
